packages:
  - docs/
  - examples/*
  - packages/*
  - .github/actions/*

catalog:
  '@hookform/resolvers': ^5.0.1
  '@types/lodash': ^4.17.20
  '@types/node': ^24.5.2
  '@types/react-dom': ^19.1.9
  '@types/react': ^19.1.13
  lodash: ^4.17.21
  react-dom: 19.2.0
  react-hook-form: ^7.64.0
  react: 19.2.0
  tailwind-merge: ^3.3.1
  tailwind-variants: ^3.1.1
  typescript: 5.9.3
  vite: ^7.1.9
  vitest: ^4.0.2

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
  - supabase
  - unrs-resolver
